name: Create Archive
on:
  push:
    tags:        
      - "v*"
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create ankiaddon
      run: 'sudo apt-get install pandoc; pip install git-cliff; make export'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "peaceful+.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
